version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "npm"
    directory: "/portal"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/shared-components"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
